name: Demo CRM CI/CD Pipeline (Docker Hub)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: demo-crm

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate image tag
      id: generate-tag
      run: |
        TAG="build-$(date +%Y%m%d)-${GITHUB_SHA:0:7}"
        echo "tag=${TAG}" >> $GITHUB_OUTPUT

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Pull, retag and push Demo CRM image
      run: |
        TAG="${{ steps.generate-tag.outputs.tag }}"
        docker pull pwstaging/demo-crm:latest
        docker tag pwstaging/demo-crm:latest ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}
        docker tag pwstaging/demo-crm:latest ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}
        docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

    - name: Create kind cluster for testing
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster --wait 300s
        kubectl cluster-info
        kubectl get nodes

    - name: Prepare and test deployment
      run: |
        TAG="${{ steps.generate-tag.outputs.tag }}"
        IMAGE="${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}"
        sed -i "s|IMAGE_PLACEHOLDER|${IMAGE}|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl wait --for=condition=available deployment/demo-crm --timeout=300s

    - name: Verify deployment works
      run: |
        kubectl get all
        kubectl port-forward deployment/demo-crm 3000:3000 &
        PORT_FORWARD_PID=$!
        sleep 15
        if curl -f http://localhost:3000/; then
          echo "Application is responding correctly!"
        else
          kubectl logs -l app=demo-crm --tail=20
          exit 1
        fi
        kill $PORT_FORWARD_PID

    - name: Display deployment instructions
      run: |
        TAG="${{ steps.generate-tag.outputs.tag }}"
        echo "1. git clone https://github.com/${{ github.repository }}.git"
        echo "2. cd demo-crm"
        echo "3. sed -i 's|IMAGE_PLACEHOLDER|${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${TAG}|g' k8s/deployment.yaml"
        echo "4. kubectl apply -f k8s/deployment.yaml"
        echo "5. kubectl wait --for=condition=available deployment/demo-crm --timeout=300s"
        echo "6. kubectl port-forward --address 0.0.0.0 deployment/demo-crm 3000:3000"

