name: Deploy Demo CRM

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Pull demo image
      run: docker pull pwstaging/demo-crm:latest

    - name: Tag image
      run: docker tag pwstaging/demo-crm:latest ${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:latest

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:latest

    - name: Set up kubectl
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl version --client
        kubectl config get-contexts

    - name: Deploy to Kubernetes
      run: |
        export KUBECONFIG=$PWD/kubeconfig
        sed -i "s|IMAGE_PLACEHOLDER|${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:latest|g" k8s/deployment.yaml
        kubectl apply -f k8s/deployment.yaml
        kubectl rollout status deployment/demo-crm
        kubectl get pods -o wide

    - name: Port-forward instructions
      run: echo "✅ To access the app, run: kubectl port-forward deployment/demo-crm 3000:3000"

